### ISSUE TITLE
dc_date validation to include BC dates

### ISSUE THREAD

**Issue by nlprj** [GIL-GALILEO/meta#316]
dc_date validation will not allow you to add BC dates. please adjust validation to allow -yyyy dates

**Comment by mksndz** [comment]
Validations already allow a "-" character in `dc_date`, as well as in `dcterms_temporal`.

![image](https://user-images.githubusercontent.com/4390340/47103029-4c849d00-d20c-11e8-873a-a9a652167e75.png)

There is, though, an issue with the year value indexing which is currently stored as an integer and as such cannot be negative, but changing that behavior is more significant work and might result in some unintended consequences we should discuss.
