### ISSUE TITLE
& not translating properly in is_shown_at and is_shown_by on batch import

### ISSUE THREAD

**Issue by nlprj** [GIL-GALILEO/meta#324]
The & character isn't being translated properly when importing xml into a batch. If no xml/html entity is used the url fails validation. If the character entity is used the url will pass validation but results in a broken link

**Comment by mksndz** [comment]
Use CDATA tags:

```
<edm_is_shown_at type="array">
  <edm_is_shown_at>
    <![CDATA[http://metis.galib.uga.edu/ssp/cgi-bin/legis-idx.pl?sessionid=518e2e7a-03c20a8e54-3823&type=toc&byte=362951]]>
  </edm_is_shown_at>
</edm_is_shown_at>```
