### ISSUE TITLE
Get a search result of multiple specific records IDs

### ISSUE THREAD

**Issue by nlprj** [GIL-GALILEO/meta#325]
Feed DLGadmin a list of specific record ids and get a search result, xml, or json response for editing by DLG. For use when an unwieldy amount of records need to be edited in large collections (250 specific records in a collection of 4000).

**Comment by mksndz** [comment]
Use https://dlgadmin.galileo.usg.edu/catalog.json?search_field=id&q=dlg_ghm_scarboro+OR+dlg_ghm_scotts-brigade

URLs can't be over 2083 chars, so you'll have to break up your queries once you hit that limit.
